# Generated by Django 4.0.2 on 2022-05-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation_mensuelle',
            name='Point_situation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stimulation',
            name='Point_situation',
            field=models.TextField(),
        ),
    ]
