# Generated by Django 4.0.2 on 2022-05-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_realisation_mensuelle_point_situation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Point_situation',
            field=models.TextField(),
        ),
    ]
